### ISSUE TITLE
Extra space added to password when copying to clipboard with Firefox

### ISSUE THREAD

**Issue by Darkle** [kalpetros/hawkpass#3]
Hi, when using Firefox and the password is copied to the clipboard, the password seems to have extra spaces surrounding the password. This doesn't seem to occur on Chrome, only Firefox.

**Comment by kalpetros** [comment]
Is this still the case with the new version?

**Comment by Darkle** [comment]
I tested in the latest Firefox on Linux and Mac and it seems fine now.
